services:
  okn-server:
    build: .
    privileged: true
    volumes:
      - /dev:/dev:rw
      - /etc/localtime:/etc/localtime:ro
      - ./credentials.json:/app/credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - TZ=Asia/Tokyo
    env_file:
      - ".env"
    restart: always
